config/routes.rb
Rails.application.routes.draw do

  root to: 'sessions#home'

  get 'home' => 'users#show', :as => :home

  get '/signup' => 'users#new'
  post '/signup' => 'users#create'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  get '/auth/google_oauth2/callback' => 'sessions#google'

#for adding an existing product to an user product collection
  resources :products, only: [:new, :create] do
    resources :user_products, only: [:new, :create]
  end

#for editing and deleting an user product.
  resources :user_products, only: [:destroy, :update]

#creates a new category.
#creates new product under category.
#shows user product list.
  resources :categories, only: [:new, :create] do
    resources :products, only: [:new, :index, :create]
    resources :user_products, only: [:index, :edit]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products

  validates :name, presence: true
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  
  has_many :user_products
  has_many :users, through: :user_products

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :user_products
  has_many :products, through: :user_products

  has_secure_password

  validates :name, :email, presence: true
  validates :email, uniqueness: true
end

app/models/user_product.rb
class UserProduct < ApplicationRecord
  belongs_to :user
  belongs_to :product

  validates :price, presence: true
  validates :price, numericality: true

  scope :product_from_category, ->(user_id, category_id) do
    joins(:product).where("user_products.user_id=? and products.category_id=?", user_id, category_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :logged_in?
  helper_method :current_user

  def logged_in?
    !!session[:user_id]
  end

  def current_user
    @current_user ||= User.find(session[:user_id]) unless session[:user_id].blank?
  end

  def redirect_if_logged_in
    if logged_in?
      redirect_to home_path
    end
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def new
  end

  def create
    @category = Category.create(category_params)
    if @category.valid?
      redirect_to home_path
    else
      flash[:notice] = "Please enter a valid category."
      redirect_to new_category_path
    end
  end

  def index
    @categories = Category.all
  end

  private

  def category_params
    params.require(:category).permit(:name)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def new
    @product = Product.new(category_id: params[:category_id])
  end

  def create
    @product = Product.create(product_params)
    if @product.valid?
      redirect_to new_product_user_product_path(@product)
    else
      flash[:notice] = "Please enter a product name."
      redirect_to new_category_product_path(category_id: params[:product][:category_id])
    end
  end

  def index
    @category = Category.find(params[:category_id])
    @products = Product.where(category_id: params[:category_id])
  end

  def show
    @product = Product.find(params[:id])
  end

  private

  def product_params
    params.require(:product).permit(:name, :category_id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :redirect_if_logged_in, only: [:home, :new]

  def home
  end

  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email]) unless params[:session][:email].blank?

    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to home_path
    else
      flash[:notice] = "Invalid email/password combination"
      redirect_to login_path
    end
  end

  def google
    @user = User.find_or_create_by(email: auth.info.email) do |user|
      user.name = auth.info.name
      user.password = SecureRandom.hex
    end

    if @user.save
      session[:user_id] = @user.id
      redirect_to home_path
    else
      redirect_to login_path
    end
  end

  def destroy
    session.clear
    redirect_to root_path
  end

  private

  def session_params
    params.require(:session).permit(:email, :password)
  end

  def auth
    request.env['omniauth.auth']
  end
end

app/controllers/user_products_controller.rb
class UserProductsController < ApplicationController
  before_action :find_product, only: [:edit, :update, :destroy]

  def index
    @category = Category.find(params[:category_id])
    @user_products = UserProduct.product_from_category(current_user, params[:category_id])
  end

  def new
    @product = Product.find(params[:product_id])
    @user_product = UserProduct.new(product_id: @product.id, user_id: current_user.id)
  end

  def create
    @user_product = UserProduct.create(user_products_params)
    if @user_product.valid?
      redirect_to_user_products_index
    else
      flash[:notice] = "Please fill price field"
      redirect_back(fallback_location: root_path)
    end
  end

  def edit
  end

  def update
    @user_product.price = params[:user_product][:price]
    @user_product.save
    redirect_to_user_products_index
  end

  def destroy
    @user_product.destroy
    redirect_to_user_products_index
  end

  private

  def user_products_params
    params.require(:user_product).permit(:user_id, :product_id, :price)
  end

  def find_product
    @user_product = UserProduct.find(params[:id])
  end

  def redirect_to_user_products_index
    redirect_to category_user_products_path(@user_product.product.category)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :redirect_if_logged_in, only: :new

  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.valid?
      session[:user_id] = @user.id
      redirect_to home_path
    else
      flash.now[:notice] = @user.errors.full_messages.join(", ")
      render :new
    end
  end

  def show
    if logged_in?
      @categories = Category.all
      @user = User.find(current_user.id)
    else
      redirect_to login_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :password, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/user_products_helper.rb
module UserProductsHelper

  def user_products_message(counter)
    case counter
    when 0
      "You don't have any products in your collection."
    when 1
      "You have one product in your collection!"
    else
      "You have #{counter} products in your collection!"
    end
  end

  def value_of_collection (user_products)
    total_value = user_products.reduce(0) {|sum, user_product| sum + user_product.price }
    "The total value of your collection is $%.2f" % total_value
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/new.html.erb
<h1>Enter a new category</h1>

<%= form_for :category, url: categories_path do |f| %>
  <div>Name: <%= f.text_field :name %></div>
  <%= f.submit "Add category" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsPortfolioProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css2?family=Fredoka+One&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Homemade+Apple&family=Indie+Flower&display=swap" rel="stylesheet">
  </head>

  <body class="application-body">
    <nav class="navbar navbar-light bg-light">
      <div class="container">
        <%= link_to root_path do %>
          <%= image_tag("logo_no_glitter_no_shadow.png", class: 'logo_image') %>
        <% end %>


        <% if logged_in? %>
          <%= link_to "Logout", logout_path, method: "delete", type: "buttton", class: "btn btn-dark" %>
        <% end %>
      </div>
    </nav>

    <div class="container">
      <% if !!flash.now[:notice] %>
        <div class="alert">
          <%= flash.now[:notice] %>
        </div>
      <% end %>
      <%= yield %>
    </div>

    <div class="footer-copyright text-center py-3">© 2020 Copyright: created by Mariel Hoepelman
     <a href="https://marielhoepelman.com"> www.marielhoepelman.com</a>
   </div>
  </body>
</html>

app/views/products/index.html.erb
<div class="user_products_wrapper">
  <h3><%= "Select from the list to add to your collection."  %></h3>

  <table class="table table-hover">
    <% @products.each do |p| %>
    <tr>
      <td><%=p.name%></td>
      <td><%= link_to "Add", new_product_user_product_path(p), type:"button", class:"btn btn-light btn-sm"%></td>
      <% end %>
    </tr>
  </table>
</div>

<div class="button_class">
  <%= link_to "Add a new product if it doesn't exist", new_category_product_path(@category), type:"button", class:"btn btn-dark"%>
</div>
<%= link_to "Back", category_user_products_path(@category), type:"button", class:"btn btn-light" %>

app/views/products/new.html.erb
<div class="new_product_wrapper">
  <h2>Enter a new Product for <%= @product.category.name %></h2>

    <%= form_for @product, url: products_path do |f| %>
      <%= f.hidden_field :category_id %>
      <div class="form-group <%= !!flash.now[:notice] ? "custom_error" : "" %> ">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control" %>
      </div>

  <div class="form-group">
    <%= f.submit "Add product", class: "btn btn-light btn_sm" %>
  </div>
  <% end %>
</div>

app/views/user_products/_form.html.erb
<%= form_for([@product, @user_product]) do |f| %>
  <div class="form-group <%= !!flash.now[:notice] ? "custom_error" : "" %> ">
    <%= f.hidden_field :product_id %>
    <%= f.hidden_field :user_id %>
    <%= f.label :price %>
    <%= f.text_field :price %>
    <%= f.submit "Update my collection" %>
  </div>
<% end %>

app/views/user_products/edit.html.erb
<div class="category_product_wrapper">
  <h3>Edit <%= @user_product.product.name %></h3>

  <%= render 'user_products/form' %>
</div>

<div class="back_button">
  <%= link_to "Back", category_user_products_path(@user_product.product.category), class: "btn btn-light" %>
</div>

app/views/user_products/index.html.erb
<div class="header_wrapper">
  <h3><%= current_user.name %>'s <%= @category.name %> collection.</h3>
</div>

  <h5><%= user_products_message(@user_products.count) %></h5>

<div class="user_products_wrapper">
  <table class="table table-hover">
    <% @user_products.each do |user_product| %>
    <tr>
      <td><%= user_product.product.name %></td>
      <td>$<%= user_product.price %></td>
      <td><%= link_to "Edit", edit_category_user_product_path(@category.id, user_product), class: "btn btn-light btn-sm" %>
      <td><%= link_to "Delete", user_product_path(user_product), method: :delete, class: "btn btn-outline-danger btn-sm" %>
    </tr>
    <% end %>
  </table>
</div>

<p><%= value_of_collection(@user_products) %></p>

<div class="button_class">
  <%= link_to "Add products to this category", category_products_path(@category), type:"button", class:"btn btn-dark" %>
</div>

<div class="back_button">
  <%= link_to "Back", home_path, class: "btn btn-light" %>
</div>

app/views/user_products/new.html.erb
<div class="category_product_wrapper">
  <h3>Add <i><%= @product.name %></i> to your <i><%= @product.category.name %></i> colection</h3>

  <%= render 'user_products/form' %>
</div>

  <%= link_to "Back", category_products_path(@product.category.id), type:"button", class:"btn btn-light" %>

app/views/users/new.html.erb
<div class="signup_wrapper">
    <div class="container">
      <h1>Sign Up</h1>

    <%= form_for @user, url: '/signup' do |f| %>

    <div class="form-group">
      <%= f.label :name %>
      <%= f.text_field :name, class: "form-control", placeholder: "Enter your name here" %>
    </div>

    <div class="form-group">
      <%= f.label :email %>
      <%= f.email_field :email, class: "form-control", placeholder: "Enter your email here" %>
    </div>

    <div class="form-group">
      <%= f.label :password %>
      <%= f.password_field :password, class: "form-control", placeholder: "Enter your password here" %>
    </div>

    <div class="form-group">
      <%= f.submit "Sign In", class: "btn btn-dark" %>
    </div>

    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<div class="header_wrapper">
  <h3> Hello <%= @user.name %> </h3>
  <h5> Click on a category to see your collection</h5>
</div>

<div class="d-flex justify-content-center flex-wrap">
  <% @categories.each do |category| %>
  <div class="categories_buttons"><%= link_to category.name, category_user_products_path(category), class: "btn btn-light" %></div>
  <% end %>
</div>

<div class="button_class">
  <%= link_to "Add a new category",  new_category_path, type:"button", class:"btn btn-dark" %>
</div>